name: jupyterlab-blockly-docs

channels:
  - conda-forge

dependencies:
  - mamba
  - myst-parser
  - pydata-sphinx-theme
  - pip:
    - jupyterlite==0.1.0b16
    - jupyterlite-sphinx
    - jupyterlite-xeus-lua>=0.3,<4
    
